# Uncomment this line to define a global platform for your project
platform :ios, '15.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Debug-dev' => :debug,
  'Debug-staging' => :debug,
  'Debug-prod' => :debug,
  'Profile' => :release,
  'Profile-dev' => :release,
  'Profile-staging' => :release,
  'Profile-prod' => :release,
  'Release' => :release,
  'Release-dev' => :release,
  'Release-staging' => :release,
  'Release-prod' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  simulator_unsupported_framework_flags = [
    '-framework "BDFaceBaseKit"',
    '-framework "IDLFaceSDK"',
  ]

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    if target.name == 'flutter_bdface_collect'
      target.frameworks_build_phase.files.each do |build_file|
        framework_name = build_file.file_ref&.display_name
        next unless ['BDFaceBaseKit.framework', 'IDLFaceSDK.framework'].include?(framework_name)

        target.frameworks_build_phase.remove_build_file(build_file)
      end
    end

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_NOTIFICATIONS=1',
      ]

      other_ldflags = config.build_settings['OTHER_LDFLAGS']
      next if other_ldflags.nil?

      simulator_ldflags =
          if other_ldflags.is_a?(Array)
            other_ldflags.reject { |flag| simulator_unsupported_framework_flags.include?(flag) }
          else
            simulator_unsupported_framework_flags.reduce(other_ldflags.dup) do |flags, framework_flag|
              flags.gsub(framework_flag, '').gsub(/\s+/, ' ').strip
            end
          end
      config.build_settings['OTHER_LDFLAGS[sdk=iphonesimulator*]'] = simulator_ldflags
    end
  end

  runner_xcconfig_paths = Dir.glob(File.join(__dir__, 'Pods', 'Target Support Files', 'Pods-Runner', 'Pods-Runner*.xcconfig'))
  runner_xcconfig_paths.each do |path|
    contents = File.read(path)
    ldflags_line = contents.lines.find { |line| line.start_with?('OTHER_LDFLAGS = ') }
    next if ldflags_line.nil?

    base_ldflags = ldflags_line.sub('OTHER_LDFLAGS = ', '').strip
    sanitized_ldflags =
        simulator_unsupported_framework_flags.reduce(base_ldflags.dup) do |flags, framework_flag|
          flags.gsub(framework_flag, '').gsub(/\s+/, ' ').strip
        end
    device_only_ldflags = "#{sanitized_ldflags} -framework \"BDFaceBaseKit\" -framework \"IDLFaceSDK\""
    replacement = <<~LDFLAGS
      OTHER_LDFLAGS = #{sanitized_ldflags}
      OTHER_LDFLAGS[sdk=iphoneos*] = #{device_only_ldflags}
      OTHER_LDFLAGS[sdk=iphonesimulator*] = $(inherited)
    LDFLAGS

    contents = contents.gsub(/OTHER_LDFLAGS = .*\n(?:OTHER_LDFLAGS\[sdk=iphoneos\*\] = .*\n)?(?:OTHER_LDFLAGS\[sdk=iphonesimulator\*\] = .*\n)?/, replacement)

    File.write(path, contents)
  end
end
