name: fundex
description: Company template app based on Clean Architecture + Riverpod.
publish_to: 'none'
version: 1.1.1+59

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.35.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  permission_handler: ^12.0.0+1
  freezed_annotation: ^3.0.0
  go_router: ^14.2.0
  dio: ^5.7.0
  json_annotation: ^4.9.0
  meta: ^1.12.0
  core_network:
    path: ../mobile_core_sdk/packages/core_network
  core_foundation:
    path: ../mobile_core_sdk/packages/core_foundation
  core_identity_auth:
    path: ../mobile_core_sdk/packages/core_identity_auth
  company_api_runtime:
    path: ../mobile_core_sdk/packages/company_api_runtime
  core_storage:
    path: ../mobile_core_sdk/packages/core_storage
  core_tool_kit:
    path: ../mobile_core_sdk/packages/core_tool_kit
  core_ui_kit:
    path: ../mobile_core_sdk/packages/core_ui_kit
  flutter_bdface_collect:
    path: plugins/flutter_bdface_collect
  aliyun_push_flutter: ^1.3.4
  firebase_core: ^4.5.0
  firebase_messaging: ^16.1.2
  firebase_crashlytics: ^5.0.8
  firebase_analytics: ^12.1.3
  package_info_plus: ^9.0.0
  lottie: ^3.3.1
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.14.0
  video_player: ^2.11.1
  cached_video_player_plus: ^4.1.0
  youtube_player_flutter: ^9.1.3
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  fluwx: ^5.7.5
  alipay_payment: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.30.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^3.0.0
  json_serializable: ^6.9.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/content/
    - assets/images/
    - assets/images/avatars/
    - assets/images/hotel-booking-ui/
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP.ttf
    - family: Noto Sans SC
      fonts:
        - asset: assets/fonts/NotoSansSC.ttf
    - family: Noto Sans TC
      fonts:
        - asset: assets/fonts/NotoSansTC.ttf

fluwx:
  app_id: wx8c903978efa432d2
  debug_logging: true
  #universal_link: https://example.com/wechat/
  ios:
    universal_link: https://gutingjun.com/

alipay_payment:
  scheme: alipayStellavia
